services:
  # ----------------------------------------
  # 1. SERVICIO DE APLICACIÓN (PHP-FPM)
  # ----------------------------------------
  app:
    # Usará el Dockerfile corregido en ./docker/Dockerfile
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: gps_tracker_app
    restart: unless-stopped
    expose:
      - 9000
    volumes:
      - .:/var/www/html
      - app_storage_data:/var/www/html/storage
      - app_cache_data:/var/www/html/bootstrap/cache
    depends_on:
      - db
      - redis
    networks:
      - app-network

  # ----------------------------------------
  # 2. SERVIDOR WEB (NGINX) - CORRECCIÓN DE MONTAJE Y COMANDO
  # ----------------------------------------
  web:
    image: nginx:stable-alpine
    container_name: gps_tracker_web
    restart: unless-stopped
    ports:
      - "80:80" # Acceso web
    volumes:
      - .:/var/www/html:ro
      # CORRECCIÓN DEFINITIVA: Montamos el archivo de configuración sobre el archivo
      # por defecto de Nginx (/etc/nginx/conf.d/default.conf).
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    # IMPORTANTE: Eliminamos el 'command' anterior. Nginx ahora usará la configuración 
    # montada en /etc/nginx/conf.d/default.conf y se iniciará normalmente.
    depends_on:
      - app
    networks:
      - app-network

  # ----------------------------------------
  # 3. BASE DE DATOS (MARIADB)
  # ----------------------------------------
  db:
    image: mariadb:10.11
    container_name: gps_tracker_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-gps_tracker}
      MYSQL_USER: ${DB_USERNAME:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      MARIADB_CHARSET: utf8mb4
      MARIADB_COLLATION: utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  # ----------------------------------------
  # 4. CACHÉ Y COLA (REDIS)
  # ----------------------------------------
  redis:
    image: redis:alpine
    container_name: gps_tracker_redis
    restart: unless-stopped
    expose:
      - 6379
    networks:
      - app-network

# ----------------------------------------
# DEFINICIÓN DE VOLÚMENES PERSISTENTES
# ----------------------------------------
volumes:
  app_storage_data:
  app_cache_data:
  db_data:

# ----------------------------------------
# DEFINICIÓN DE REDES
# ----------------------------------------
networks:
  app-network:
    driver: bridge