services:
  # ----------------------------------------
  # 1. SERVICIO DE APLICACIÓN (PHP-FPM)
  # ----------------------------------------
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: gps_tracker_app
    restart: unless-stopped
    expose:
      - 9000
    volumes:
      - .:/var/www/html
      - app_storage_data:/var/www/html/storage
      - app_cache_data:/var/www/html/bootstrap/cache
    depends_on:
      - db
      - redis
    networks:
      - app-network

  # ----------------------------------------
  # 2. SERVIDOR WEB (NGINX)
  # ----------------------------------------
  web:
    image: nginx:stable-alpine
    container_name: gps_tracker_web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html:ro
      # Montaje del directorio de configuración Nginx
      - ./docker/nginx-config:/etc/nginx/conf.d:ro 
      - nginx_cache_data:/var/cache/nginx
    depends_on:
      - app
    networks:
      - app-network

  # ----------------------------------------
  # 3. BASE DE DATOS (MARIADB)
  # ----------------------------------------
  db:
    image: mariadb:10.11
    container_name: gps_tracker_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      # Credenciales: deben coincidir con las de tu archivo .env
      MYSQL_DATABASE: ${DB_DATABASE:-gpstracker}
      MYSQL_USER: ${DB_USERNAME:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  # ----------------------------------------
  # 4. CACHÉ Y COLA (REDIS)
  # ----------------------------------------
  redis:
    image: redis:alpine
    container_name: gps_tracker_redis
    restart: unless-stopped
    expose:
      - 6379
    networks:
      - app-network

  # ----------------------------------------
  # 5. GESTOR DE BASE DE DATOS (PHPMYADMIN)
  # ----------------------------------------
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: gps_tracker_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80" # Acceso por el puerto 8080 de tu host
    environment:
      # phpMyAdmin apunta al nombre del servicio de MariaDB
      PMA_HOST: db 
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
    depends_on:
      - db
    networks:
      - app-network

# ----------------------------------------
# DEFINICIÓN DE VOLÚMENES PERSISTENTES
# ----------------------------------------
volumes:
  app_storage_data:
  app_cache_data:
  db_data:
  nginx_cache_data: 

# ----------------------------------------
# DEFINICIÓN DE REDES
# ----------------------------------------
networks:
  app-network:
    driver: bridge